xmgrace -pexec "arrange(2,1,0.15,0,0)" \
    -graph 0 -block $1.dyn.dat -settype xy -bxy 1:6 \
    -pexec "s0.x = s0.x / $2" \
    -pexec "yaxis label \"2T/|W|\"" \
    -pexec "xaxis ticklabel off" \
    -graph 1 -block $1.dyn.dat -settype xy -bxy 1:10 \
    -graph 1 -block $1.dyn.dat -settype xy -bxy 1:20 \
    -pexec "s0.x = s0.x / $2" \
    -pexec "s1.x = s1.x / $2" \
    -pexec "yaxis label \"E\stot\N, E\stot\N+E\soops\N [NB units]\"" \
    -pexec "xaxis label \"t [t\srh\N]\""
