xmgrace -pexec "arrange(2,2,.15,0.1,0)" \
    -graph 0 -block $1.dyn.dat -settype xy -bxy 1:10 \
    -graph 0 -block $1.dyn.dat -settype xy -bxy 1:20 \
    -pexec "yaxis label \"E\stot\N, E\stot\N+E\soops\N [FP units]\"" \
    -pexec "xaxis ticklabel off" \
    -graph 1 -block $1.dyn.dat -settype xy -bxy 1:6 \
    -pexec "yaxis label place opposite" \
    -pexec "yaxis ticklabel place opposite" \
    -pexec "yaxis label \"2T/|W|\"" \
    -pexec "xaxis ticklabel off" \
    -graph 2 -log y -block $1.dyn.dat -settype xy -bxy 1:8 \
    -pexec "yaxis label \"r\sc\N [r\sNB\N]\"" \
    -pexec "xaxis label \"t [FP units]\"" \
    -graph 3 -nxy $1.lagrad.dat -log y \
    -pexec "yaxis label place opposite" \
    -pexec "yaxis ticklabel place opposite" \
    -pexec "yaxis label \"r\slagr\N [r\sNB\N]\"" \
    -pexec "xaxis label \"t [FP units]\""
